### ISSUE TITLE
Issues bundling for production with `camelcase` dep

### ISSUE THREAD

**Issue by zsherman** [syntax-tree/hastscript#3]
Not sure if I'm the only one to run into this issue, but he takes a hard stance here https://github.com/sindresorhus/ama/issues/446. Problem is this causes uglify to choke in most systems using webpack since vendor dependencies are generally not babelified.

Do we really need to import a library here or can we just use a simple camel case function like:

```
const hyphenToCamelCase = str => str.replace(/-([a-z])/g, (m, w) => w.toUpperCase())
```

to handle the majority of these cases?

**Comment by wooorm** [comment]
This package uses camelcase v3, uglify shouldn’t choke on it. What are you seeing?

**Comment by zsherman** [comment]
Ah strange, I had the latest version of camelcase installed for some reason which includes `let`, `const`, etc. Sorry about that!

**Comment by wooorm** [comment]
That can happen, but was probably introduced by another dep!
