### ISSUE TITLE
How to create boolean attributes?

### ISSUE THREAD

**Issue by Justineo** [syntax-tree/hastscript#5]
```js
h('button', { disabled: true })
h('button', { disabled: false })
```

will produce:

```html
<button disabled="true"></button>
<button disabled="false"></button>
```

Is there any chance that we can make it produce this?

```html
<button disabled></button>
<button></button>
```

(And this is gonna be a breaking change...)

**Comment by wooorm** [comment]
This should work. How are you stringifying nodes?

**Comment by wooorm** [comment]
@Justineo Ping!

**Comment by Justineo** [comment]
Sorry for the delay. I used it pretty much like the following (not real code):

```js
import remark from 'remark'
import remarkToRehype from 'remark-to-rehype'
import raw from 'rehype-raw'
import custom from './rehype-custom'
import html from 'rehype-stringify'

remark()
  // some remark plugins omitted here
  .use(remarkToRehype, { allowDangerousHTML: true })
  .use(raw)
  .use(custom) // ← inserted some node via hastscript in here with boolean attribute
  .use(html, { allowDangerousHTML: true })
```

---

BTW, I'm using `remark` to build docs for our project. The source code of the docs will be later converted into Vue.js components (with demos and their source code displayed along with APIs, so I need to include some raw HTML in there) and hosted on a Nuxt.js server. I found `remark` and the whole “ecosystem” is actually the best Markdown transformer/compiler I've ever used. Thanks for the great work!

**Comment by wooorm** [comment]
Thanks for the kind words, glad to hear, I appreciate it!

I just did this and it seems to work! 🤷‍♂️ Your issue must be with something else, what’s in `rehype-custom`?

```js
var toHTML = require('hast-util-to-html');
var h = require('hastscript');

var tree = h('div', [
  h('button', {disabled: true}),
  h('button', {disabled: false})
]);

console.log(toHTML(tree)); // => <div><button disabled></button><button></button></div>
```

**Comment by Justineo** [comment]
Ah, I see where the problem is. I was using a custom attribute `v-pre` but `hast-util-to-html` is stripping values only for known boolean attributes.

```js
var toHTML = require('hast-util-to-html');
var h = require('hastscript');

var tree = h('div', [
  h('button', {'v-pre': true}),
  h('button', {'v-pre': false})
]);

console.log(toHTML(tree)); // => <div><button v-pre="true"></button><button v-pre="false"></button></div>
```

**Comment by Justineo** [comment]
@wooorm Is there any way I can define a custom boolean attribute here?

**Comment by wooorm** [comment]
Hmm, no. We can discuss this further on `hast-util-to-html` though? Maybe we can drop the [` && info.overloadedBoolean` part here](https://github.com/syntax-tree/hast-util-to-html/blob/06c268d1e4d20e398adaf5a275227775739cee18/lib/element.js#L115)?
