### ISSUE TITLE
Support camelCased source properties

### ISSUE THREAD

**Issue by StarpTech** [syntax-tree/hastscript#6]
Hi,
I would like to use the hype ecosystem to build my own html formatter but I'm facing with a big issue. I use a fork of parse5 in order to handle element attributes case-sensitive for web frameworks like Angular, VueJs.

hastscript doesn't respect (in my case parse5 tree) as the source of truth (https://github.com/syntax-tree/hastscript/blob/master/index.js#L144) because it converts all attributes to camelCases, which I think is wrong from the point of view of a parser tool. But anyway I understand the reasons and my project isn't html5 compliant but it would be very great to have that flexibility in rehype precisely because rehype serve as a general interface between html parsers.

* I couldn't find in the [specification ](https://github.com/syntax-tree/hast) that attributes are handled case-insensitive.

Thank you!

**Comment by StarpTech** [comment]
Related https://github.com/syntax-tree/hast-util-to-html/issues/5

**Comment by wooorm** [comment]
My thoughts are these:

* For HTML, we need proper SVG support. I’m planning on working that in the future. But this may also need a change to the syntax tree
* For non-HTML things, like angular and vue, we could create a new XML-based parser/stringifier. Maybe something based on [this](https://github.com/rgrove/parse-xml).

**Comment by wooorm** [comment]
And for the spec, you can see it in the [property name](https://github.com/syntax-tree/hast#property-names) section!

**Comment by StarpTech** [comment]
But even with the use of a less strict html parser we would break the HAST specification right? Currently, I solve it by forking the relevant projects and make them case-sensitive aware but this breaks HAST :( Do you plan to change the specs for exactly that case or only for proper svg support ?

**Comment by wooorm** [comment]
I’m not really sure how to do it otherwise. HAST is for HTML. And in JS and plugins you’d like to use `.className` instead of `.class`.

Also, is this really a problem here, or in `hast-util-to-html`?

**Comment by StarpTech** [comment]
It's a problem in many places

* `hastscript` https://github.com/syntax-tree/hastscript/blob/master/index.js#L144
* `hast-util-to-html` https://github.com/syntax-tree/hast-util-to-html/blob/master/lib/element.js#L132

Do you see a way to modify attributes only when known html attributes are used plus maybe a check for camelCased svg elements?

e.g for

Hastscript
```
title => 'title' //known
FOO => 'FOO' // unknown
viewBox => 'viewBox' //known but svg
tab-index => 'tabIndex' //known
class => 'className' //known
```

A possible solution would be to add this information here https://github.com/wooorm/property-information/blob/master/index.js#L231 and propoagate it through all relevant packages.

**Comment by StarpTech** [comment]
In this way, we are still compatible but don't interfere in how a parser provide it's attributes. WDYT?

**Comment by wooorm** [comment]
Would you also say that:

```
tITLE => 'title' //known
VIEWBOX => 'viewBox' //known but svg
Class => 'className' //known
```

?

**Comment by StarpTech** [comment]
yes and for unknown attributes it's passed as it was received from the parser.

**Comment by wooorm** [comment]
Alright!

In which cases should `viewBox` be known (treated case-insensitively)?

* always
* when processing a know SVG element?
* when processing a know SVG / HTML / MathML element?
* when processing a (sub)tree as SVG?
* Only on the `svg` element

(these options should also work for e.g., `muted` on HTMLs `audio`)

**Comment by StarpTech** [comment]
> In which cases should viewBox be known (treated case-insensitively)?

Good question. I propose

* case-insensitively, only when processing an [SVG viewport](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/viewBox).

**Comment by StarpTech** [comment]
You could use this [map](https://github.com/inikulin/parse5/blob/3bfa7d9f3297f96772a8eb26d9cfc4d79314af8b/packages/parse5/lib/common/foreign-content.js#L20)

**Comment by StarpTech** [comment]
@wooorm do you have concrete ideas on how we can implement it? Would you accept a PR?

**Comment by wooorm** [comment]
Hey @StarpTech!

I thought about it a bit and I’d like to work on this now. For starters, this issue is now first tracked in https://github.com/wooorm/property-information/issues/6. When that is done, we can work on updating it throughout the ecosystem.

I’ll close this now, if you have any further comments please post them there!

P.S. thanks for offering to help. I’ve spent today thinking and working on it, and I have a clear idea of where this should go. I’ll try to get a MVP working soon and will let you know if I need help!

**Comment by StarpTech** [comment]
Hi @woorm, thanks for the update. Great, that my proposal found acceptance!
