### ISSUE TITLE
Strict comparison between self cannot occur

### ISSUE THREAD

**Issue by StarpTech** [syntax-tree/hastscript#7]
This can never occur: https://github.com/syntax-tree/hastscript/blob/master/index.js#L112

**Comment by wooorm** [comment]
Yes it can, if the value is [NaN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN)!

**Comment by StarpTech** [comment]
Good to know but for readability, I prefer `Number.isNaN()` 😄

**Comment by wooorm** [comment]
Yeah I agree but that was added later in JavaScript!
