### ISSUE TITLE
Add docs for different `h()` algorithms

### ISSUE THREAD

**Issue by KazimirPodolski** [syntax-tree/hastscript#9]
There is no consistency with `h()` behavoiur:
* [virtual-hyperscript](https://github.com/Matt-Esch/virtual-dom/blob/master/virtual-hyperscript/README.md) uses property `attributes` for attribues (and requires them to be kebab-case).
* [snabbdom](https://github.com/snabbdom/snabbdom) uses property `attrs` for the same puprpose.
* hyperscript?
* whatever ancestor of hyperscript?

And all of them *does not document anything*. Actual behaviour is salvaged from experiment and issues.

It would be really nice if hastscript would document what is actual format of `h()` arguments. Sorry if I'm missing something and this all is false.

**Comment by wooorm** [comment]
This is all true, but that’s exactly why this project is here: the deal with all those changes. You can find out about how they work, by reading their docs. This project just supports all their interfaces, but it’s not this project’s place to document those projects? 🤔

I’m not sure what you suggest to do, and I feel like this is not the place, so closing for now.

**Comment by KazimirPodolski** [comment]
It was not about documenting those projects, but about documenting hastscript. Another projects is just an example of inconsistent behaviour.

To be more clear, these things are not covered in hastscript docs and require experimenting and reading sources :
* Classes in selector + classes in properties: how do they combine?
* `className` seems to do classes in properties, however it is a property of a DOM element rather than HTML element.
* camelCase vs kebab-case in properties names. Generally, does hastscript work with HTML elements or DOM elements?
* SVG namespaces?
* Any other special treatment of properties.

**Comment by wooorm** [comment]
Oh whoops, I thought this issue was reported on [`hast-to-hyperscript`](https://github.com/syntax-tree/hast-to-hyperscript), because you mentioned some other flavours. Sorry, I misread.

To find out more about all your points above, please click through to HAST, it’s a really well defined specification. It answers all your points.

I also remember there being a project to spec and stabilise all the different hyperscript-like interfaces, but can’t find it anymore unfortunately :(

**Comment by KazimirPodolski** [comment]
There is an attempt to standardise hyperscript https://github.com/hyperhype/hyperscript/issues/66 but it went nowhere.

Thanks, I'll check it out there.

**Comment by wooorm** [comment]
Yeah I think there was some other repo as well, but I can’t find it anymore :(
